begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, private, extensions;

select plan(26);
select has_column('public', 'reviewer_reliability', 'source_provider');
select has_column('public', 'reviewer_reliability', 'estimator_version');
select has_column('public', 'reviewer_reliability', 'snapshot_revision');
select col_is_fk('public', 'reviewer_reliability', 'supersedes_reliability_pk', 'snapshot lineage is a foreign key');
select has_column('public', 'reviewer_reliability', 'sample_count');
select has_column('public', 'reviewer_reliability', 'control_accuracy');
select has_column('public', 'reviewer_reliability', 'sensitivity');
select has_column('public', 'reviewer_reliability', 'specificity');
select has_column('public', 'reviewer_reliability', 'pairwise_agreement');
select has_column('public', 'reviewer_reliability', 'krippendorff_alpha');
select has_column('public', 'reviewer_reliability', 'adjudicated_overlap');
select has_column('public', 'reviewer_reliability', 'interval_level');
select has_column('public', 'reviewer_reliability', 'evidence_fingerprint');
select has_column('public', 'reviewer_reliability', 'blockers');
select has_index('public', 'reviewer_reliability', 'reviewer_reliability_current_domain_idx', 'current domain lookup is indexed');
select has_index('public', 'reviewer_reliability', 'reviewer_reliability_supersedes_pk_idx', 'supersession FK is indexed');
select has_trigger('public', 'reviewer_reliability', 'reviewer_reliability_enforce_snapshot', 'snapshot policy trigger exists');
select has_trigger('public', 'reviewer_reliability', 'reviewer_reliability_reject_mutation', 'snapshot append-only trigger exists');
select ok(not has_table_privilege('authenticated', 'public.reviewer_reliability', 'insert'), 'reviewers cannot insert scores');
select ok(not has_table_privilege('authenticated', 'public.reviewer_reliability', 'update'), 'reviewers cannot alter scores');
select ok(has_table_privilege('service_role', 'public.reviewer_reliability', 'insert'), 'service may append estimates');
select ok(not has_table_privilege('service_role', 'public.reviewer_reliability', 'update'), 'service cannot overwrite estimates');
select ok((select relrowsecurity from pg_class where oid = 'public.reviewer_reliability'::regclass), 'reliability remains RLS protected');
select ok(exists(select 1 from pg_policies where schemaname = 'public' and policyname = 'reviewer_reliability_self_read'), 'reviewers retain private self access');
select ok(exists(select 1 from pg_policies where schemaname = 'public' and policyname = 'reviewer_reliability_curator_read'), 'authorized curators retain governance access');
select ok(not has_table_privilege('anon', 'public.reviewer_reliability', 'select'), 'public cannot read private reliability');
select * from finish();
rollback;
