begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, private, extensions;

select plan(25);
select has_column('public', 'consensus', 'revision');
select has_column('public', 'consensus', 'reviewer_weights_applied');
select has_column('public', 'consensus', 'reliability_snapshot_fingerprint');
select has_column('public', 'consensus', 'adjudication_event_fingerprint');
select has_column('public', 'consensus', 'layer_summary');
select col_is_fk('public', 'consensus', 'adjudication_event_fingerprint', 'adjudication links exact evidence');
select has_index('public', 'consensus', 'consensus_layer_revision_key', 'layer revision is unique');
select has_index('public', 'consensus', 'consensus_current_layer_idx', 'current layer lookup is indexed');
select has_index('public', 'consensus', 'consensus_adjudication_event_fingerprint_idx', 'adjudication FK is indexed');
select has_trigger('public', 'consensus', 'consensus_enforce_layered_snapshot', 'layer policy trigger exists');
select has_trigger('public', 'consensus', 'consensus_reject_mutation', 'consensus is append only');
select has_function('private', 'enforce_layered_consensus_snapshot', array[]::text[], 'layer policy helper exists');
select has_function('private', 'reject_consensus_mutation', array[]::text[], 'mutation rejection helper exists');
select ok(not has_table_privilege('authenticated', 'public.consensus', 'insert'), 'reviewers cannot insert consensus');
select ok(not has_table_privilege('authenticated', 'public.consensus', 'update'), 'reviewers cannot alter consensus');
select ok(has_table_privilege('service_role', 'public.consensus', 'insert'), 'service may append consensus');
select ok(not has_table_privilege('service_role', 'public.consensus', 'update'), 'service cannot overwrite consensus');
select ok((select relrowsecurity from pg_class where oid = 'public.consensus'::regclass), 'consensus remains RLS protected');
select ok(exists(select 1 from pg_policies where schemaname = 'public' and policyname = 'consensus_respondent_read'), 'respondents retain evidence access');
select ok(exists(select 1 from pg_policies where schemaname = 'public' and policyname = 'consensus_curator_read'), 'curators retain governance access');
select col_not_null('public', 'consensus', 'revision');
select col_not_null('public', 'consensus', 'reviewer_weights_applied');
select col_not_null('public', 'consensus', 'layer_summary');
select ok(not has_table_privilege('anon', 'public.consensus', 'select'), 'public cannot read respondent consensus');
select ok(not has_table_privilege('service_role', 'public.consensus', 'delete'), 'service cannot delete consensus');
select * from finish();
rollback;
