begin;
create extension if not exists pgtap with schema extensions;
set search_path = public, private, extensions;

select plan(28);
select has_table('public', 'flickr_application_approvals');
select has_table('public', 'flickr_removal_cases');
select has_table('public', 'flickr_display_assets');
select has_table('public', 'flickr_removal_events');
select has_view('public', 'flickr_public_display_projection');
select has_column('public', 'flickr_display_assets', 'photographer');
select has_column('public', 'flickr_display_assets', 'attribution');
select has_column('public', 'flickr_display_assets', 'source_url');
select has_column('public', 'flickr_display_assets', 'licence_id');
select has_column('public', 'flickr_display_assets', 'licence_url');
select has_column('public', 'flickr_display_assets', 'cache_expires_at');
select has_column('public', 'flickr_display_assets', 'removal_case_pk');
select col_is_fk('public', 'flickr_display_assets', 'flickr_photo_pk', 'display source is a Flickr record');
select col_is_fk('public', 'flickr_display_assets', 'media_object_pk', 'display source is a governed media object');
select col_is_fk('public', 'flickr_display_assets', 'application_approval_pk', 'display requires application approval');
select col_is_fk('public', 'flickr_display_assets', 'removal_case_pk', 'display retains removal lineage');
select has_trigger('public', 'flickr_display_assets', 'flickr_display_assets_validate', 'display assets fail closed');
select has_trigger('public', 'flickr_removal_cases', 'flickr_removal_cases_quarantine', 'removal cases quarantine immediately');
select has_function('private', 'validate_flickr_display_asset', array[]::text[], 'display validator exists');
select has_function('private', 'quarantine_flickr_removal_case', array[]::text[], 'removal quarantine exists');
select has_index('public', 'flickr_display_assets', 'flickr_display_assets_eligible_expiry_idx', 'eligible expiry lookup is partial-indexed');
select has_index('public', 'flickr_removal_cases', 'flickr_removal_cases_deadline_idx', '24-hour deadline lookup is indexed');
select ok((select relrowsecurity from pg_class where oid = 'public.flickr_display_assets'::regclass), 'display assets are RLS protected');
select ok((select relrowsecurity from pg_class where oid = 'public.flickr_removal_cases'::regclass), 'removal cases are RLS protected');
select ok(not has_table_privilege('anon', 'public.flickr_display_assets', 'select'), 'anonymous users cannot bypass the service projection');
select ok(not has_table_privilege('authenticated', 'public.flickr_display_assets', 'insert'), 'browser roles cannot publish Flickr photos');
select ok(has_table_privilege('service_role', 'public.flickr_display_assets', 'insert'), 'service may admit display assets');
select ok(not has_table_privilege('service_role', 'public.flickr_removal_cases', 'update'), 'removal cases are append only');
select * from finish();
rollback;
